- src/main/java/frc/robot/FieldConstants.java
While testing, I noticed that the center game piece positions were a little off...
> Fix centerlineX field constant

- src/main/java/org/littletonrobotics/frc2024/RobotState.java
Use transforms for vision updates
> Use transforms when applying vision pose

- trajectory_native/src/trajectory_service.cpp
Based on https://github.com/SleipnirGroup/Choreo/pull/204
> Fix trajectory wrapping

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/DriveConstants.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/trajectory/HolonomicTrajectory.java
> Trajectory controller improvements

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/GyroIOPigeon2.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/ModuleIOKrakenFOC.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/intake/IntakeIOKrakenFOC.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmIOKrakenFOC.java
> Use "*" bus name for all CANivore devices

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> Set rollers and superstructure to final

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Module.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmIO.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmIOKrakenFOC.java
I put the alerts for the arm and drive in the same group, but I left out the flywheels and rollers since those have to be changed in their own place.
> Added alerts for arm and drive

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/backpack/Backpack.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/backpack/BackpackIO.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/backpack/BackpackIOSim.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/backpack/BackpackIOSparkFlex.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
> Add backpack and amp controls

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/DriveConstants.java
Update wheel radius, fix characterization swerve setpoint
> Update wheel radius, fix characterization swerve setpoint

- src/main/java/org/littletonrobotics/frc2024/Robot.java
Add alert for high bus utilization
> Add logs for CANivore bus utiliization

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
Add override to enable subwoofer scoring
> Add override to arm aiming

- src/main/java/org/littletonrobotics/frc2024/Robot.java
- src/main/java/org/littletonrobotics/frc2024/RobotState.java
> Aiming parameter improvements

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/DriveConstants.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/trajectory/GenerateTrajectories.java
> Drive constants updates

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/controllers/HeadingController.java
> Heading controller improvements

- src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
> Remove unused variables

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
- src/main/java/org/littletonrobotics/frc2024/RobotState.java
> Add controls for shot compensation

- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
Unused except for logging and shouldn't be exposed publicly
> Remove arm "getSetpoint" method

- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
Shoot note when feeding shooter
> Show intaked notes when shooter staged

- src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/intake/IntakeIOKrakenFOC.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmConstants.java
> Add CAN IDs for compbot

- src/main/java/org/littletonrobotics/frc2024/RobotState.java
> Remove unused shot angle from map

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
Thorough testing has been completed
> Add super poop

- src/main/java/org/littletonrobotics/frc2024/Constants.java
- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
Use right trigger for pooping
Amp without autoDrive turns robot to 90
> Driver controls for scoring

- src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
- src/main/java/org/littletonrobotics/frc2024/subsystems/leds/Leds.java
> Give driver boost led mode
